export const SKILLS = [
  { id: "javascript", label: "JavaScript", icon: "LuCode" },
  { id: "python", label: "Python", icon: "LuCode" },
  { id: "java", label: "Java", icon: "LuCode" },
  { id: "csharp", label: "C#", icon: "LuCode" },
  { id: "react", label: "React", icon: "LuCode" },
  { id: "vue", label: "Vue.js", icon: "LuCode" },
  { id: "angular", label: "Angular", icon: "LuCode" },
  { id: "node", label: "Node.js", icon: "LuDatabase" },
  { id: "mongodb", label: "MongoDB", icon: "LuDatabase" },
  { id: "sql", label: "SQL", icon: "LuDatabase" },
  { id: "aws", label: "AWS", icon: "LuCloud" },
  { id: "azure", label: "Azure", icon: "LuCloud" },
  { id: "docker", label: "Docker", icon: "LuCloud" },
  { id: "kubernetes", label: "Kubernetes", icon: "LuCloud" },
  { id: "uiux", label: "UI/UX Design", icon: "LuPenTool" },
  { id: "figma", label: "Figma", icon: "LuPenTool" },
  { id: "photoshop", label: "Photoshop", icon: "LuPenTool" },
  { id: "security", label: "Cybersecurity", icon: "LuShield" },
  { id: "ml", label: "Machine Learning", icon: "LuTrendingUp" },
  { id: "ai", label: "AI", icon: "LuBrain" },
  { id: "product", label: "Product Management", icon: "LuBriefcase" },
  { id: "marketing", label: "Marketing", icon: "LuTrendingUp" },
];
